/**
 * @file memo.ts
 * Single source of truth for all type definitions used across the app.
 * All interfaces and constants are declared here; other files import from this file.
 */

/** Union type of all possible memo colors (union prevents typos) */
export type MemoColor = 'white' | 'yellow' | 'pink' | 'blue' | 'green' | 'purple' | 'orange';

/**
 * Array used to guarantee rendering order of color swatches.
 * Must always be kept in sync with the MemoColor type.
 */
export const MEMO_COLORS: MemoColor[] = ['white', 'yellow', 'pink', 'blue', 'green', 'purple', 'orange'];

/** Default size applied when a new memo is created (pixels) */
export const DEFAULT_MEMO_SIZE = { width: 200, height: 200 };

/** Default color applied when a new memo is created */
export const DEFAULT_MEMO_COLOR: MemoColor = 'white';

/**
 * Represents the position of a memo within the canvas.
 * Both x and y are pixel values with the canvas top-left corner as the origin (0, 0).
 * (Not relative to the viewport)
 */
export interface MemoPosition {
  x: number; // distance from the left edge of the canvas (px)
  y: number; // distance from the top edge of the canvas (px)
}

/**
 * Represents the width and height of a memo.
 * Currently fixed size; this type will be used as-is when resize support is added.
 */
export interface MemoSize {
  width: number;  // memo width (px)
  height: number; // memo height (px)
}

/**
 * Complete data structure for a single memo.
 * Both the store and localStorage persist data in this shape.
 */
export interface Memo {
  /** Unique identifier generated by crypto.randomUUID() */
  id: string;

  /** Body text of the memo (currently plain text only) */
  content: string;

  /** Absolute position within the canvas */
  position: MemoPosition;

  /** Size of the memo box */
  size: MemoSize;

  /** Memo background color */
  color: MemoColor;

  /** Timestamp when the memo was first created (ms via Date.now()). Never changes. */
  createdAt: number;

  /**
   * Timestamp when the memo was last modified (ms via Date.now()).
   * Updated whenever content, color, position, etc. change.
   * createdAt === updatedAt means the memo was "just created".
   */
  updatedAt: number;
}

/**
 * Top-level structure saved to localStorage.
 * The version field allows safe migration if the data schema changes.
 */
export interface PersistedState {
  memos: Memo[];
  /**
   * Schema version number.
   * Increment this when adding new fields or changing existing field structures,
   * and add a conversion block to the migrate() function in localStorage.ts.
   */
  version: number;
}

/** Schema version currently used by the app. Compared with PersistedState.version to decide whether migration is needed. */
export const CURRENT_VERSION = 1;
